/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class UserServiceTest {
    @Test void testGetUserRole() {
        UserService us = new UserService();
        assertEquals("Admin -- User", us.getUserRole());
    }
}

